apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: nginx
    command: [ "/usr/bin/curl","-XGET", "http://host.docker.internal:9999/metrics/job/lms-api/instance/${HOSTNAME}"]
  restartPolicy: OnFailure