apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-vol-configmap
  name: deploy-vol-configmap
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-vol-configmap
  template:
    metadata:
      labels:
        app: deploy-vol-configmap
    spec:
      containers:
      - name: sleepy
        image: sysnet4admin/sleepy
        command: ["/bin/sh","-c"]
        args:
        - |
          sleep 3600
        volumeMounts:
        - name: appconfigvol
          mountPath: /etc/sleepy.d
      volumes:
      - name: appconfigvol
        configMap:
          name: sleepy-config