apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
    - name: container
      image: tmkube/init
      envFrom:
      - configMapRef:
          name: cmd-dev
      - secretRef:
          name: sec-dev